[package]
name = "scamper"
version = "0.1.0"
authors = ["David Young <david.young@nccgroup.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wkhtmltoimage"]

wkhtmltoimage = ["wkhtmltopdf"]
wkhtmltoimage_bin = [ ]

[dependencies]
clap = "3.0.0-beta.1"
rdp-rs = "0.1.0"
image = "0.23.4"
simplelog = "0.8"
log = "0.4.8"
url = "2.1.1"
nmap_xml_parser = "0.2.0"
wkhtmltopdf = { "optional" = true, "git" = "https://github.com/sciguy16/wkhtmltopdf-rs", branch = "image-implementation" }