name: Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: General checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

#      - name: Install cargo-outdated
#        run: cargo install cargo-outdated

#      - name: Install cargo-audit
#        run: cargo install cargo-audit

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

#      - name: Run cargo outdated
#        uses: actions-rs/cargo@v1
#        with:
#          command: outdated
#          args: --exit-code 1

#      - name: Run cargo audit
#        uses: actions-rs/cargo@v1
#        with:
#          command: audit

  test_ubuntu:
    name: Run tests on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Fetch shared library
        run: ./fetch-wkhtmltopdf-lib.py linux

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -L .
          LD_LIBRARY_PATH: .

  test_windows:
    name: Run tests on windows-latest
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install python dependencies
        run: python -m pip install -r fetch-wkhtmltopdf-lib-requirements.txt

      - name: Fetch shared library
        run: python fetch-wkhtmltopdf-lib.py windows

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -L .

  test_macos:
    name: Run tests on macOS-latest
    runs-on: macOS-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install python dependencies
        run: python3 -m pip install -r fetch-wkhtmltopdf-lib-requirements.txt

      - name: Fetch shared library
        run: ./fetch-wkhtmltopdf-lib.py macos

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: -L .